version: "3.8"

networks:
  kafka_network:
    external: true

services:
  api-gateway:
    build: 
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"   
    environment:
      PORT: 8080
      DB_HOST: host.docker.internal
      DB_PORT: 1433
      DB_USER: DEV
      DB_PASSWORD: "1234"
      DB_NAME: ID_SERVICE_DB
      JWT_SECRET: mysupersecretkey
      TZ: America/Santiago
    networks:
      - kafka_network
