version: '3.8'

networks:
  orders-service_kafka_network:
    external: true  # 📌 Usa la misma red de `orders-service`

services:
  packaging-service:
    build: .
    container_name: packaging-service
    restart: always
    ports:
      - "5003:5003"
    environment:
      PORT: 5003
      DB_HOST: host.docker.internal 
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: packaging_service_db
      DB_PORT: 3306
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: packaging-service
    networks:
      - orders-service_kafka_network


      