version: '3.8'

networks:
  orders-service_kafka_network:
    external: true  # 📌 Usa la misma red de `orders-service`

# Nueva red donde está Kafka
  kafka_network:
    external: true    

services:
  picking-service:
    build: .
    container_name: picking-service
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      DB_HOST: host.docker.internal
      DB_USER: williams
      DB_PASSWORD: Mimbral1579
      DB_NAME: orders_service_db
      DB_PORT: 1433
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: picking-service
    networks:
      - orders-service_kafka_network
      - kafka_network     
