version: '3.8'

networks:
  orders-service_kafka_network:
    external: true

services:
  id-service:
    build: .
    container_name: vtex-service
    restart: always
    ports:
      - "5007:5007"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "win-hp03dio6fsk:192.168.0.165"
    dns:
      - 127.0.0.11
      - 8.8.8.8         
      - 1.1.1.1 
    environment:
      PORT: 5017
      DB_HOST: host.docker.internal
      DB_USER: williams
      DB_PASSWORD: Mimbral1579
      DB_NAME: VTEX_SYNC
      DB_PORT: 1433
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: id-service
      VTEX_APP_KEY: ${VTEX_APP_KEY}
      VTEX_APP_TOKEN: ${VTEX_APP_TOKEN}
      VTEX_ACCOUNT: ${VTEX_ACCOUNT}
      VTEX_ENVIRONMENT: ${VTEX_ENVIRONMENT}
      SAP_BASE_URL: ${SAP_BASE_URL}
      SAP_COMPANY_DB: ${SAP_COMPANY_DB}
      SAP_USERNAME: ${SAP_USERNAME}
      SAP_PASSWORD: ${SAP_PASSWORD}
    networks:
      - orders-service_kafka_network

