version: '3.8'

networks:
  orders-service_kafka_network:
    external: true  # 📌 Usa la misma red de `orders-service`

services:
  sap-integration-service:
    build: .
    container_name: sap-integration-service
    restart: always
    ports:
      - "5004:5004"
    environment:
      PORT: 5004
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: sap-integration-service
    networks:
      - orders-service_kafka_network