version: '3.8'

networks:
  kafka_network:  # 📌 Definir la red compartida
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: "-Djava.net.preferIPv4Stack=true"
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  orders-service:
    build: .
    container_name: orders-service
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - kafka
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "win-hp03dio6fsk:192.168.0.165"
    dns:
      - 127.0.0.1
      - 8.8.8.8         
      - 1.1.1.1  
    environment:
      PORT: 5000
      DB_HOST: host.docker.internal

      DB_USER: DEV
      DB_PASSWORD: 1234
      DB_NAME: orders_service_db
      DB_PORT: 1433
      VTEX_APP_KEY: ${VTEX_APP_KEY}
      VTEX_APP_TOKEN: ${VTEX_APP_TOKEN}
      SAP_SL_BASE_URL:   ${SAP_SL_BASE_URL}
      SAP_SL_COMPANYDB:  ${SAP_SL_COMPANYDB}
      SAP_SL_USER:       ${SAP_SL_USER}
      SAP_SL_PASSWORD:   ${SAP_SL_PASSWORD}
      SAP_SL_SESSION:     ${SAP_SL_SESSION}
      KAFKA_BROKER: kafka:9092  # Asegura que Kafka es accesible usando el hostname "kafka"
      KAFKA_CLIENT_ID: orders-service
    networks:
      - kafka_network